# Generated by Django 5.1.4 on 2026-05-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('terminate', '终止')], max_length=20)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '变更明细',
                'verbose_name_plural': '变更明细',
            },
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', '起草中'), ('submitted', '已提交'), ('approved', '已审批'), ('rejected', '已驳回'), ('applied', '已生效'), ('reverted', '已撤销')], default='draft', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', '手工'), ('excel', '导入'), ('api', 'API')], default='manual', max_length=20)),
            ],
            options={
                'verbose_name': '变更批次',
                'verbose_name_plural': '变更批次',
            },
        ),
    ]
