# Generated by Django 5.1.4 on 2026-05-13 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changesets', '0001_initial'),
        ('schemas', '0001_initial'),
        ('temporal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changeentry',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='temporal.entity'),
        ),
        migrations.AddField(
            model_name='changeentry',
            name='new_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='temporal.temporalrecord'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_changesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeset',
            name='revert_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_by_sets', to='changesets.changeset'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schemas.dataschema'),
        ),
        migrations.AddField(
            model_name='changeentry',
            name='change_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='changesets.changeset'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['schema', '-applied_at'], name='idx_changeset_schema_applied'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_changeset_creator'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['status', '-created_at'], name='idx_changeset_status'),
        ),
        migrations.AddIndex(
            model_name='changeentry',
            index=models.Index(fields=['change_set', 'action'], name='idx_changeentry_set_action'),
        ),
        migrations.AddIndex(
            model_name='changeentry',
            index=models.Index(fields=['entity', 'valid_from'], name='idx_changeentry_entity_vfrom'),
        ),
        migrations.AddConstraint(
            model_name='changeentry',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='changeentry_valid_range_ok'),
        ),
        migrations.AddConstraint(
            model_name='changeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'create'), ('data_after__isnull', False), ('data_before__isnull', True)), models.Q(('action', 'update'), ('data_after__isnull', False), ('data_before__isnull', False)), models.Q(('action', 'terminate'), ('data_after__isnull', True), ('data_before__isnull', False)), _connector='OR'), name='changeentry_payload_matches_action'),
        ),
    ]
