# Generated by Django 5.1.4 on 2026-05-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='source',
            field=models.CharField(choices=[('manual', '手工'), ('excel', '导入'), ('api', 'API'), ('revert', '撤销')], default='manual', max_length=20),
        ),
    ]
