# Generated by Django 5.1.4 on 2026-06-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment_mention", "评论提及"),
                            ("comment_reply", "评论回复"),
                            ("approval_assigned", "审批待办"),
                            ("approval_updated", "审批更新"),
                            ("export_finished", "导出完成"),
                            ("export_failed", "导出失败"),
                            ("system_notice", "系统通知"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("success", "成功"),
                            ("warning", "警告"),
                            ("error", "错误"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                ("target_kind", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("target_url", models.CharField(blank=True, max_length=500)),
                ("payload", models.JSONField(default=dict)),
                ("dedupe_key", models.CharField(blank=True, max_length=191)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "-created_at"],
                        name="idx_notification_unread",
                    ),
                    models.Index(
                        fields=["recipient", "archived_at", "-created_at"],
                        name="idx_notification_inbox",
                    ),
                    models.Index(
                        fields=["type", "-created_at"], name="idx_notification_type_created"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        fields=("recipient", "dedupe_key"),
                        name="uniq_notification_recipient_dedupe",
                    )
                ],
            },
        ),
    ]
