# Generated by Django 5.1.4 on 2026-06-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment_mention", "评论提及"),
                            ("comment_reply", "评论回复"),
                            ("approval_assigned", "审批待办"),
                            ("approval_updated", "审批更新"),
                            ("export_finished", "导出完成"),
                            ("export_failed", "导出失败"),
                            ("system_notice", "系统通知"),
                        ],
                        max_length=64,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("external_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知偏好",
                "verbose_name_plural": "通知偏好",
                "indexes": [models.Index(fields=["user", "type"], name="idx_notif_pref_user_type")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "type"), name="uniq_notification_preference_user_type"
                    )
                ],
            },
        ),
    ]
