# Generated by Django 5.1.4 on 2026-05-23 13:18

import apps.workbench.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schemas", "0002_expand_schema_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkbenchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("data_card", "资料卡"), ("note", "笔记"), ("material", "材料")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workbench_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台条目",
                "verbose_name_plural": "工作台条目",
            },
        ),
        migrations.CreateModel(
            name="WorkbenchDataCardDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("organization", "组织"),
                            ("people", "人员"),
                            ("social_security", "社保"),
                            ("finance", "财务"),
                            ("policy", "政策"),
                            ("import_template", "导入模板"),
                            ("common_text", "常用文本"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("applicable_year", models.PositiveIntegerField(blank=True, null=True)),
                ("applicable_region", models.CharField(blank=True, max_length=120)),
                ("applicable_subject", models.CharField(blank=True, max_length=120)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending_confirm", "待确认"),
                            ("confirmed", "已确认"),
                            ("expired", "已过期"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("remark", models.TextField(blank=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_card_detail",
                        to="workbench.workbenchitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台资料卡明细",
                "verbose_name_plural": "工作台资料卡明细",
            },
        ),
        migrations.CreateModel(
            name="WorkbenchLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workbench_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="workbench.workbenchitem",
                    ),
                ),
                (
                    "target_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="workbench.workbenchitem",
                    ),
                ),
                (
                    "target_schema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbench_links",
                        to="schemas.dataschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台关联",
                "verbose_name_plural": "工作台关联",
            },
        ),
        migrations.CreateModel(
            name="WorkbenchMaterialDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to=apps.workbench.models.workbench_material_upload_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "preview_status",
                    models.CharField(
                        choices=[
                            ("none", "无"),
                            ("image", "图片"),
                            ("text", "文本"),
                            ("failed", "失败"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_detail",
                        to="workbench.workbenchitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台材料明细",
                "verbose_name_plural": "工作台材料明细",
            },
        ),
        migrations.CreateModel(
            name="WorkbenchNoteDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("markdown_content", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pre_schema", "建表前"),
                            ("field_design", "字段设计"),
                            ("excel_import", "Excel 导入"),
                            ("validation", "校验"),
                            ("approval", "审批"),
                            ("stats_export", "统计导出"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("pending_confirm", "待确认"),
                            ("confirmed", "已确认"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_detail",
                        to="workbench.workbenchitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台笔记明细",
                "verbose_name_plural": "工作台笔记明细",
            },
        ),
        migrations.CreateModel(
            name="WorkbenchUserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("material_quota_bytes", models.PositiveBigIntegerField(default=1073741824)),
                ("upload_disabled", models.BooleanField(default=False)),
                ("storage_used_bytes", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbench_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台用户设置",
                "verbose_name_plural": "工作台用户设置",
            },
        ),
        migrations.CreateModel(
            name="WorkbenchDataCardField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("value", models.TextField(blank=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("number", "数字"),
                            ("date", "日期"),
                            ("money", "金额"),
                            ("percent", "百分比"),
                            ("boolean", "布尔"),
                            ("url", "链接"),
                            ("longtext", "长文本"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("remark", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="workbench.workbenchdatacarddetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台资料项",
                "verbose_name_plural": "工作台资料项",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["card", "sort_order"], name="idx_wb_field_card_sort")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(
                fields=["owner", "type", "deleted_at"], name="idx_wb_item_owner_type"
            ),
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(fields=["owner", "is_pinned"], name="idx_wb_item_owner_pin"),
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(fields=["owner", "-last_used_at"], name="idx_wb_item_owner_last"),
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(fields=["owner", "-updated_at"], name="idx_wb_item_owner_upd"),
        ),
        migrations.AddIndex(
            model_name="workbenchlink",
            index=models.Index(fields=["owner", "source_item"], name="idx_wb_link_owner_src"),
        ),
        migrations.AddIndex(
            model_name="workbenchlink",
            index=models.Index(fields=["owner", "target_schema"], name="idx_wb_link_owner_sch"),
        ),
        migrations.AddConstraint(
            model_name="workbenchlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_item__isnull", False), ("target_schema__isnull", True)),
                    models.Q(("target_item__isnull", True), ("target_schema__isnull", False)),
                    _connector="OR",
                ),
                name="wb_link_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="workbenchlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_item__isnull", False)),
                fields=("owner", "source_item", "target_item"),
                name="uniq_wb_link_item_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="workbenchlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_schema__isnull", False)),
                fields=("owner", "source_item", "target_schema"),
                name="uniq_wb_link_schema_target",
            ),
        ),
        migrations.AddIndex(
            model_name="workbenchmaterialdetail",
            index=models.Index(fields=["content_type"], name="idx_wb_mat_content"),
        ),
        migrations.AddIndex(
            model_name="workbenchmaterialdetail",
            index=models.Index(fields=["checksum"], name="idx_wb_mat_checksum"),
        ),
    ]
