# Generated by Django 5.1.4 on 2026-05-24 00:18

import apps.workbench.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0002_expand_schema_icon"),
        ("workbench", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkbenchMaterialChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "未准备"),
                            ("uploaded", "已上传"),
                            ("pending_confirm", "待确认"),
                            ("not_applicable", "不适用"),
                        ],
                        default="missing",
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_checklist_items",
                        to="workbench.workbenchitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workbench_material_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbench_checklist_items",
                        to="schemas.dataschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作台材料清单项",
                "verbose_name_plural": "工作台材料清单项",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "schema", "sort_order"], name="idx_wb_chk_owner_sort"
                    )
                ],
            },
            bases=(apps.workbench.models.FullCleanOnSaveMixin, models.Model),
        ),
    ]
