# Generated by Django 5.1.4 on 2026-05-13 00:38

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(default=dict)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'indexes': [models.Index(fields=['actor', '-created_at'], name='idx_audit_actor_created'), models.Index(fields=['target_type', 'target_id'], name='idx_audit_target'), models.Index(fields=['is_sensitive', '-created_at'], name='idx_audit_sensitive'), django.contrib.postgres.indexes.GinIndex(fields=['detail'], name='idx_audit_detail_gin')],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION audit_log_immutable()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_log is immutable';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER audit_log_no_update
            BEFORE UPDATE ON audit_auditlog
            FOR EACH ROW EXECUTE FUNCTION audit_log_immutable();

            CREATE TRIGGER audit_log_no_delete
            BEFORE DELETE ON audit_auditlog
            FOR EACH ROW EXECUTE FUNCTION audit_log_immutable();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_auditlog;
            DROP TRIGGER IF EXISTS audit_log_no_update ON audit_auditlog;
            DROP FUNCTION IF EXISTS audit_log_immutable();
            """,
        ),
    ]
