# Generated by Django 5.1.4 on 2026-05-25 12:36

import apps.stats.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schemas", "0003_dataschema_label_print_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "job_code",
                    models.CharField(
                        default=apps.stats.models.generate_export_job_code,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "export_scope",
                    models.CharField(
                        choices=[("current_view", "当前视图")],
                        default="current_view",
                        max_length=32,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(choices=[("csv", "CSV"), ("xlsx", "Excel")], max_length=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("expired", "已过期"),
                            ("canceled", "已取消"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("snapshot_key", models.CharField(max_length=64)),
                ("query_snapshot", models.JSONField(default=dict)),
                ("row_count_estimate", models.PositiveIntegerField(default=0)),
                ("row_count_actual", models.PositiveIntegerField(blank=True, null=True)),
                ("risk_flags", models.JSONField(default=list)),
                ("risk_details", models.JSONField(default=dict)),
                ("risk_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=255, upload_to=apps.stats.models.export_job_upload_to
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=127)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to="schemas.dataschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "导出任务",
                "verbose_name_plural": "导出任务",
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"], name="idx_export_job_owner_created"
                    ),
                    models.Index(
                        fields=["owner", "status", "-created_at"],
                        name="idx_export_job_owner_status",
                    ),
                    models.Index(
                        fields=["schema", "-created_at"], name="idx_export_job_schema_created"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="idx_export_job_status_created"
                    ),
                    models.Index(fields=["expires_at"], name="idx_export_job_expires"),
                    models.Index(
                        fields=["owner", "schema", "export_scope", "export_format", "snapshot_key"],
                        name="idx_export_job_snapshot",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=("owner", "schema", "export_scope", "export_format", "snapshot_key"),
                        name="uniq_export_job_active_snapshot",
                    )
                ],
            },
        ),
    ]
