# Generated by Django 5.1.4 on 2026-05-13 00:38

import apps.temporal.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changesets', '0001_initial'),
        ('schemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_code', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schemas.dataschema')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
            },
        ),
        migrations.CreateModel(
            name='TemporalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveIntegerField()),
                ('data_payload', models.JSONField(default=dict)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_superseded', models.BooleanField(default=False)),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changesets.changeset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='temporal.entity')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='temporal.temporalrecord')),
            ],
            options={
                'verbose_name': '时态记录',
                'verbose_name_plural': '时态记录',
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['schema', 'business_code'], name='idx_entity_schema_code'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('schema', 'business_code'), name='uniq_entity_schema_business_code'),
        ),
        migrations.AddIndex(
            model_name='temporalrecord',
            index=models.Index(fields=['entity', 'valid_from'], name='idx_tr_entity_vfrom'),
        ),
        migrations.AddIndex(
            model_name='temporalrecord',
            index=models.Index(fields=['entity', '-valid_from'], name='idx_tr_entity_vfrom_desc'),
        ),
        migrations.AddIndex(
            model_name='temporalrecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data_payload'], name='idx_tr_data_payload_gin'),
        ),
        migrations.AddConstraint(
            model_name='temporalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='valid_range_ok'),
        ),
        migrations.AddConstraint(
            model_name='temporalrecord',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_superseded', False)), expressions=[('entity', '='), (apps.temporal.models.DateRange('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='exclude_active_temporal_overlap'),
        ),
    ]
