# Generated by Django 5.1.4 on 2026-05-13 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0002_initial'),
        ('temporal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='temporalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='temporal_record_schema_version_positive'),
        ),
    ]
