# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.temporal.models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0001_initial"),
        ("temporal", "0002_temporalrecord_temporal_record_schema_version_positive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldFileAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.CharField(db_index=True, max_length=64)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.temporal.models.field_asset_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_file_assets",
                        to="schemas.dataschema",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "字段文件资产",
                "verbose_name_plural": "字段文件资产",
                "indexes": [
                    models.Index(
                        fields=["schema", "field_key"],
                        name="idx_file_asset_schema_field",
                    ),
                    models.Index(
                        fields=["uploaded_by", "-created_at"],
                        name="idx_file_asset_uploader",
                    ),
                ],
            },
        ),
    ]
