# Generated by Django 5.1.4 on 2026-06-05 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("wechat_web", "微信网站"),
                            ("wechat_miniprogram", "微信小程序"),
                            ("dingtalk", "钉钉"),
                            ("qq_web", "QQ 网站"),
                            ("qq_miniprogram", "QQ 小程序"),
                        ],
                        max_length=32,
                    ),
                ),
                ("tenant_id", models.CharField(blank=True, max_length=128, null=True)),
                ("provider_account_id", models.CharField(max_length=191)),
                ("union_id", models.CharField(blank=True, max_length=191, null=True)),
                ("open_id", models.CharField(blank=True, max_length=191, null=True)),
                ("external_username", models.CharField(blank=True, max_length=191)),
                ("nickname", models.CharField(blank=True, max_length=191)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("raw_profile", models.JSONField(default=dict)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "第三方身份",
                "verbose_name_plural": "第三方身份",
                "indexes": [
                    models.Index(
                        fields=["user", "provider"], name="idx_ext_identity_user_provider"
                    ),
                    models.Index(
                        fields=["provider", "tenant_id", "open_id"], name="idx_ext_identity_openid"
                    ),
                    models.Index(fields=["last_login_at"], name="idx_ext_identity_last_login"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "tenant_id", "provider_account_id"),
                        name="uniq_external_identity_stable_account",
                        nulls_distinct=False,
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("union_id__isnull", False)),
                        fields=("provider", "tenant_id", "union_id"),
                        name="uniq_external_identity_union_id",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthLoginIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", models.CharField(max_length=128, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("wechat_web", "微信网站"),
                            ("wechat_miniprogram", "微信小程序"),
                            ("dingtalk", "钉钉"),
                            ("qq_web", "QQ 网站"),
                            ("qq_miniprogram", "QQ 小程序"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("register_login", "注册或登录"), ("bind", "绑定")], max_length=32
                    ),
                ),
                ("next_path", models.CharField(default="/", max_length=500)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_login_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth 登录意图",
                "verbose_name_plural": "OAuth 登录意图",
                "indexes": [
                    models.Index(
                        fields=["provider", "mode", "created_at"], name="idx_oauth_intent_lookup"
                    ),
                    models.Index(fields=["expires_at"], name="idx_oauth_intent_expires"),
                ],
            },
        ),
    ]
