# Generated by Django 5.1.4 on 2026-05-22 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0002_expand_schema_icon'),
        ('temporal', '0003_fieldfileasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '作废'), ('lost', '遗失'), ('replaced', '已替换')], default='active', max_length=20)),
                ('template_code', models.CharField(default='asset_standard', max_length=64)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('print_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='temporal.entity')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_entity_labels', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_entity_labels', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='labels.entitylabel')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_entity_labels', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labels', to='schemas.dataschema')),
            ],
            options={
                'verbose_name': '实体物理标签',
                'verbose_name_plural': '实体物理标签',
            },
        ),
        migrations.CreateModel(
            name='LabelScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_code_hash', models.CharField(db_index=True, max_length=80)),
                ('outcome', models.CharField(choices=[('resolved', '已解析'), ('login_required', '需要登录'), ('denied', '无权限'), ('revoked', '已作废'), ('replaced', '已替换'), ('not_found', '未找到'), ('invalid', '无效')], max_length=20)),
                ('source', models.CharField(choices=[('qr_url', '二维码 URL'), ('barcode_input', '一维码输入'), ('scanner_console', '扫码工作台'), ('mobile_camera', '手机相机'), ('api', 'API')], default='api', max_length=32)),
                ('ip_hash', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('raw_input_kind', models.CharField(choices=[('code', '标签码'), ('url', 'URL'), ('unknown', '未知')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_scan_events', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_scan_events', to='temporal.entity')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='labels.entitylabel')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_scan_events', to='schemas.dataschema')),
            ],
            options={
                'verbose_name': '标签扫码事件',
                'verbose_name_plural': '标签扫码事件',
            },
        ),
        migrations.AddIndex(
            model_name='entitylabel',
            index=models.Index(fields=['entity', 'status'], name='idx_label_entity_status'),
        ),
        migrations.AddIndex(
            model_name='entitylabel',
            index=models.Index(fields=['schema', 'status'], name='idx_label_schema_status'),
        ),
        migrations.AddIndex(
            model_name='entitylabel',
            index=models.Index(fields=['label_code'], name='idx_label_code'),
        ),
        migrations.AddIndex(
            model_name='entitylabel',
            index=models.Index(fields=['last_scanned_at'], name='idx_label_last_scan'),
        ),
        migrations.AddConstraint(
            model_name='entitylabel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('entity',), name='uniq_active_label_per_entity'),
        ),
        migrations.AddIndex(
            model_name='labelscanevent',
            index=models.Index(fields=['label', '-created_at'], name='idx_scan_label_created'),
        ),
        migrations.AddIndex(
            model_name='labelscanevent',
            index=models.Index(fields=['schema', '-created_at'], name='idx_scan_schema_created'),
        ),
        migrations.AddIndex(
            model_name='labelscanevent',
            index=models.Index(fields=['outcome', '-created_at'], name='idx_scan_outcome_created'),
        ),
    ]
