# Generated by Django 5.1.4 on 2026-06-05 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("changesets", "0003_alter_changeset_source"),
        ("schemas", "0004_expand_period_units"),
        ("temporal", "0004_fieldfileasset_docx_extraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("schema", "表"),
                            ("row", "行"),
                            ("cell", "单元格"),
                            ("changeset_entry", "变更明细"),
                        ],
                        max_length=32,
                    ),
                ),
                ("field_key", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at_context_date", models.DateField(blank=True, null=True)),
                ("record_valid_from_snapshot", models.DateField(blank=True, null=True)),
                ("record_valid_to_snapshot", models.DateField(blank=True, null=True)),
                ("value_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "未解决"), ("resolved", "已解决")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                (
                    "change_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment_threads",
                        to="changesets.changeentry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_comment_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment_threads",
                        to="temporal.entity",
                    ),
                ),
                (
                    "record_at_creation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_threads_at_creation",
                        to="temporal.temporalrecord",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comment_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="schemas.dataschema"
                    ),
                ),
            ],
            options={
                "verbose_name": "评论线程",
                "verbose_name_plural": "评论线程",
            },
        ),
        migrations.CreateModel(
            name="CommentReadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="comments.commentthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论已读状态",
                "verbose_name_plural": "评论已读状态",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField()),
                (
                    "body_format",
                    models.CharField(choices=[("plain", "纯文本")], default="plain", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="comments.commentthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
        migrations.CreateModel(
            name="CommentMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "评论提及",
                "verbose_name_plural": "评论提及",
                "indexes": [
                    models.Index(fields=["user", "comment"], name="idx_mention_user_comment")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comment", "user"), name="uniq_comment_mention_user"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(
                fields=["schema", "anchor_type", "entity", "field_key", "status"],
                name="idx_comment_anchor_status",
            ),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(
                fields=["schema", "last_activity_at"], name="idx_comment_schema_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(fields=["entity", "field_key"], name="idx_comment_entity_field"),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(fields=["change_entry"], name="idx_comment_change_entry"),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(
                fields=["created_by", "last_activity_at"], name="idx_comment_creator_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="commentreadstate",
            index=models.Index(fields=["user", "thread"], name="idx_read_state_user_thread"),
        ),
        migrations.AddConstraint(
            model_name="commentreadstate",
            constraint=models.UniqueConstraint(
                fields=("thread", "user"), name="uniq_comment_read_user"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["thread", "created_at"], name="idx_comment_thread_created"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_by", "created_at"], name="idx_comment_author_created"
            ),
        ),
    ]
