# Generated by Django 5.1.4 on 2026-05-13 00:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='schema_code 只能使用小写字母、数字和下划线，且必须以字母开头', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('temporal_mode', models.CharField(choices=[('continuous', '连续型'), ('periodic', '周期型')], default='continuous', max_length=20)),
                ('period_unit', models.CharField(blank=True, choices=[('month', '月'), ('quarter', '季'), ('year', '年')], max_length=20, null=True)),
                ('identity_field_key', models.CharField(max_length=64)),
                ('fields_config', models.JSONField(default=list)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('config_migrated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('private', '私有'), ('shared', '共享'), ('public', '公共')], default='private', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '数据表',
                'verbose_name_plural': '数据表',
            },
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('fields_config', models.JSONField(default=list)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schemas.dataschema')),
            ],
            options={
                'verbose_name': 'Schema 版本',
                'verbose_name_plural': 'Schema 版本',
            },
        ),
        migrations.CreateModel(
            name='TableCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', '编辑者'), ('viewer', '查看者')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='schemas.dataschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '表协作者',
                'verbose_name_plural': '表协作者',
            },
        ),
        migrations.AddIndex(
            model_name='dataschema',
            index=models.Index(fields=['owner', 'visibility'], name='idx_schema_owner_visibility'),
        ),
        migrations.AddIndex(
            model_name='dataschema',
            index=models.Index(fields=['schema_code'], name='idx_schema_code'),
        ),
        migrations.AddConstraint(
            model_name='dataschema',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period_unit__isnull', True), ('temporal_mode', 'continuous')), models.Q(('period_unit__isnull', False), ('temporal_mode', 'periodic')), _connector='OR'), name='schema_period_unit_matches_mode'),
        ),
        migrations.AddConstraint(
            model_name='dataschema',
            constraint=models.CheckConstraint(condition=models.Q(('current_version__gte', 1)), name='schema_current_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='dataschema',
            constraint=models.CheckConstraint(condition=models.Q(('schema_code__regex', '^[a-z][a-z0-9_]*$')), name='schema_code_format'),
        ),
        migrations.AddIndex(
            model_name='schemaversion',
            index=models.Index(fields=['schema', '-version'], name='idx_schema_version_desc'),
        ),
        migrations.AddConstraint(
            model_name='schemaversion',
            constraint=models.UniqueConstraint(fields=('schema', 'version'), name='uniq_schema_version'),
        ),
        migrations.AddConstraint(
            model_name='schemaversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='schema_version_positive'),
        ),
        migrations.AddIndex(
            model_name='tablecollaborator',
            index=models.Index(fields=['user', 'role'], name='idx_collaborator_user_role'),
        ),
        migrations.AddConstraint(
            model_name='tablecollaborator',
            constraint=models.UniqueConstraint(fields=('schema', 'user'), name='uniq_table_collaborator_schema_user'),
        ),
    ]
